export {
    Accessibility,
    AttachFile,
    AttachFile as PaperClip,
    Block,
    BlockRounded,
    CalendarToday as Calendar,
    Cancel,
    Cancel as XCircle,
    CancelPresentation as XSquare,
    Check,
    CheckBox,
    CheckBox as CheckSquare,
    CheckBoxOutlineBlank,
    CheckCircle,
    ChevronLeft,
    ChevronRight,
    Close,
    Close as X,
    CloudUpload,
    Description,
    Description as FileText,
    Edit,
    BorderColor as Edit3,
    Error,
    Error as AlertCircle,
    ExitToApp,
    ExitToApp as LogOut,
    ExpandLess,
    ExpandLess as ChevronUp,
    ExpandMore,
    ExpandMore as ChevronDown,
    GetApp,
    GetApp as Download,
    Help,
    Help as HelpCircle,
    IndeterminateCheckBox,
    Info,
    InsertPhoto,
    Menu,
    MoreVert as MoreVertical,
    Publish,
    Person,
    Person as User,
    RadioButtonChecked,
    RadioButtonUnchecked,
    ReplyRounded,
    Sync,
    ZoomIn,
    ZoomOut
  } from '@material-ui/icons'